
# Site settings
title: Linxuan Li
name: Linxuan Li
subtitle:  Geophysics
email: lxli_0@whu.edu.cn
description: >
   Geophysics
baseurl: ""
url: "https://lxli0.github.io/"
github_username:  pesoto
disqus_baseurl: "https://lxli0.github.io/"
disqus_shortname: https-pesoto-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Paul E. Soto"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: pesoto
    url: https://github.com/lxli0
    desc: Fork me on GitHub
    share: false

  - name: Researchgate
    icon: researchgate
    username: Linxuan Li
    url: https://www.researchgate.net/profile/Lin-Xuan-Li
    desc: Connect with me on LinkedIn
    share: true
